src/client.js
since key wasnt removed `getCabalKeys` would still return the key.
=> remove cabal key while removing cabal

api.md, src/cabal-details.js, src/client.js
this pr introduces the modular event listeners we have been craving :3
it needs better documentation and the cli has not been rewritten using only the new listeners. the old update event is still emitted, so integrating the new listeners can be done in a pieacemeal fashion. 
i believe the `init` event will be useful for cli & desktop alike : )
`debug` is also introduced as a module, which allows for really nice logs of events using e.g. the following invocation
```
DEBUG="cabal-client" node cli.js <cabal-key> 2> cabal-debug-log.txt
```
see below for the list of events that are emitted, and please review to find any bugs <3
events and payloads are documented as `<type>`: `<payload>|empty`:
* `init`: empty
* `nick-change`: `{ key, newNick, oldNick }`
* `user-updated`: `{ key, user }`
* …
=> Add modular event listeners

src/commands.js
I had a dangling reference to `chalk` left over while refactoring so `/channels` was broken. This fixes the text form and also exposes object info for custom ansi or html rendering.
=> object form for /channels and fix reference to chalk

package-lock.json, src/cabal-details.js, src/commands.js
this PR adds the `/ids` command, which is intended to be used such that long identifiers are appended to nicknames, to uniquely identify them ([see the cabal-cli PR](https://github.com/cabal-club/cabal-cli/pull/179))
the mechanism for determining to show ids or not is the new CabalDetails property `showIds` i.e. use `cabal.showIds` to determine if you should show the extended nickname or not
=> add /ids to toggle ids on/off

src/client.js
For [the moderation grant](https://opencollective.com/cabal-club/updates/cabal-x-subjective-moderation-mozilla-grant) we have been talking about enabling people to set a default administrator, or moderator. 
The reasoning is, without that ability, entering a cabal for the first time as a new person risks exposing people to a bunch of trolls or other malicious participants which have already been blocked by the regular people in the cabal.
The way to do it with out dns, which at least I advocate for, is setting moderators & administrators via URL parameters, as in:
```
cabal://<cabal key>?mod=<public key of moderator>&admin=<public key of administrator>
```
The tricky part seemed to be how we add support for that to the [DNS shortnames](https://github.com/datprotocol/dat-dns/pull/15), …
=> Expand dat-dns regexes, enabling sharing default mod key via dns

package.json, src/cabal-details.js, src/channel-details.js, src/client.js, src/commands.js, src/moderation.js
this pr moves some of the moderation commands from `commands.js` to a new class, and exposes a bunch of methods. 
the intent is for clients other than the terminal client to be able to easily use moderation commands. e.g. cabal desktop can tie menu actions to moderation commands more easily
* a bunch of moderation commands are now exposed on each cabal-details instance e.g. `details.moderation`, see moderation.js for the full listing atm
* `/moderation` is a new command for showing moderation related commands
* output from `/help` has been fixed by making use of monotonic timestamps
* adds new event, `command`: `details.on('command', ({ command, arg })`
=> add moderation class, new cmd /moderation, and fix cmd output

src/cabal-details.js, src/client.js
after #39 landed, it seems like the `init` event was not being emitted correctly for desktop. i had a look around and i might have found the culprit
cc @nikolaiwarner
=> fix init event not being emitted correctly

src/cabal-details.js, src/channel-details.js, src/commands.js, src/moderation.js
this pr adds
* `/actions` - list historic actions by you or your currently applied moderators
* `/roles` - shows the admins/mods you have applied atm
* new virtual message type: `chat/moderation` see https://github.com/cabal-club/cabal-cli/pull/192 for how it is used cc @nikolaiwarner 
* adds support for displaying realtime moderation actions by other moderators/admins, see cabal-cli pr above for what that looks like
* fixes a bug with setFlag, also reverts _setFlag to return a stream instead of promise
* fixes ordering of virtual messages (they weren't being sorted properly before)
* adds better user feedback for various moderation actions
=> improve user feedback when interacting with moderation

package.json, src/client.js, src/commands.js
Hi friends!
This PR adds _whisperlinks_. Whisperlinks are user defined, shortlived, shortname aliases for a cabal key. They look something like 
```
whisper://workshop-1ee
```
where the first part identifies the string as a whisper link, `workshop` is the user defined alias, and the `-1ee` suffix are three first hex characters of the cabal key being shared (which helps verify the joined cabal, as well as disambiguate names & prevent already-unlikely name collisions).
Whisperlinks are shortlived, currently terminating after 5 minutes. A whisperlink can be used multiple times before it self-terminates, and it will sync over LAN as well as the internet (it uses [hyperswarm](https://github.com/hyperswarm/hyperswarm), under the hood)
Anyone can create a whisperlink for a cabal they are in by …
=> add whisperlinks

src/commands.js
This PR adds the `/search` command, which makes use of @timgoeller's [excellent search PR](https://github.com/cabal-club/cabal-client/pull/44).
The syntax at the moment is simple: `/search <term> (--ch <channel>)`. If `--ch` is omitted, the currently focused channel is searched.
=> Implement /search <term> (--ch <channel>)

package.json, src/cabal-details.js, src/client.js, src/commands.js, test/test.js
this pr solves some mistakes when resolving cabal keys that have an admin/mod key set. previously, the full length resolved uri would be used internally, instead of the properly scrubbed cabal key. this caused side effects, such as the screenshot, below.
_there should only be one folder, and it should not be the one with an admin key stuck in it_
this pr also adds a `/whoiskey <public key>` command that lets you know what the user name is of that public key.
i needed it for some other debugging and i cba to add a separate pr ^^'
=> sanitize resolved shortnames better, improve scrub

src/client.js
this pr adds support for setting a custom port to listen for [hyperswarm](https://github.com/hyperswarm/hyperswarm) (i.e. find cabal peers) traffic on. it is related to https://github.com/cabal-club/cabal-core/pull/101 and https://github.com/cabal-club/cabal-core/issues/98
the port is set in the config object which is passed to `cabal-client` from client implementations
```
config: {
temp: <boolean>,
dbdir: <string, filepath to storage location>,
preferredPort: <valid port number>
}
```
=> read preferredPort from config, send to core

src/cabal-details.js, src/commands.js
This PR makes all slash commands' `info` event also include **which command** triggered the event. As a consequence, handling command output in react-style apps like cabal-desktop should be a lot easier and [less haphazard](https://github.com/cabal-club/cabal-desktop/blob/master/app/actions.js#L623-L631).
`CabalDetails._res` has been converted from being an object, returning three functions (`info`, `error`, `end`), to a function. The function takes the command type as an argument, and calling it returns the same object as previously—the key difference being that the three functions have had their **payload annotated to include the command type**. 
(n.b. This is not _entirely_ correct, as only `info` has been annotated to include the `command` key,)
The emitted `command` event has also …
=> Desktop friendly command events

src/cabal-details.js, src/commands.js
This fixes a case where moderation commands would not work on peers without nicknames. Ironically, this is an important case to solve for a moderation system (as low-effort trolls are more likely to spew gall w/o any nickname).
=> Allow hiding nickless peers

src/commands.js, src/moderation.js
When this PR is finished+merged, we will have full support for taking moderation actions in specific channels (as opposed to the broader cabal).
Before this PR, the syntax for e.g. hiding was:
```
/hide <person.suffix> <reason string>
```
After this PR, the above will still be supported, as well as extended to allow:
```
/hide <person.suffix> --reason <reason string> --channel <channel name>
```
I am currently mulling over allowing multiple --channel options in a single command:
```
/ hide <person.suffix> --reason <reason string> --channel ch1 --channel ch2 --channel ch3
```
You can also omit either flag (--reason, --channel) and it will still work.
=> Channel-specific moderation actions

package.json, src/cabal-details.js, src/channel-details.js, src/commands.js, src/initialization-callbacks.js, src/user.js
This PR adds implements support for channel archiving, enabling people to hide channels from being listed. This can be useful for abuse mitigation as well as handling mistakenly created channels, or cleaning up unused ones.
The system is centered around the subjective moderation system. This means that:
1. the local user can always archive/restore channels (you are always an admin from your own perspective)
2. the local user's moderators and admins will have their archiving actions be applied to the local user's view
3. if rando mcrando archives a channel, it will have no effect for the local user (unless the above applies)
4. people can still join & talk in archived channels, they will just be hidden from channel listings
Currently implemented commands:
```
/archives, /archived
view the …
```
=> Channel archiving

package.json
Quickens install times from several minutes to seconds on machines lacking prebuilt binaries.
=> Upgrade cabal-core for faster installs (sodium-native)

package.json, src/cabal-details.js, src/channel-details.js, src/commands.js, src/initialization-callbacks.js
This PR adds support for cabal-core's private message functionality in a few different ways:
* a new `CabalDetails.publishPrivateMessage` function has been added
* `CabalDetails.getPrivateMessageList` returns a list of channel names corresponding to ongoing PMs for the local user
* `CabalDetails.isChannelPrivate(channel)` returns true if the passed in channel is a private message channel, false otherwise
* `CabalDetails.publishMessage` now redirects a published message to `publishPrivateMessage` if it is used to post a message to a private message channel
* A new convention was introduced to limit malicious use in clients: Channel names conforming to the hypercore public key format are forbidden in cabal-client as names for regular channel names (i.e. no channel names that are 64 hex …
=> Add support for private messages

src/cabal-details.js, src/channel-details.js
this patch expands the `cabal-details:getChannels` function with an additional parameter `onlyJoined`
from the docs:
```
onlyJoined - Determines whether to limit returned channels to only those that are joined or not. Defaults to false.
```
used primarily by the cli client atm
=> getChannels: add onlyJoined param

src/initialization-callbacks.js
this is already happening [here](https://github.com/cabal-club/cabal-client/blob/master/src/initialization-callbacks.js#L75), and is creating duplicate events.
=> remove duplication of channel events

src/cabal-details.js
The previous ordering would cause a null access exception when checking `pmInstance.joined` even if the null check
was triggered.
Fixes #90
=> Reorder PM null check

src/client.js, test/test.js
The `addCabal` function wasn't previously propagating name resolution errors, causing cabal-cli to crash when invoked with a bad cabal name, like `cabal ewoijffwejlkw`.
=> Handles case of being unable to resolve a key.
